AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Cluster – Fargate + EC2 Managed Instances"

Parameters:
  ECSAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id

Resources:

  #########################################
  # CloudWatch Log Group
  #########################################
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/ecs-teste
      RetentionInDays: 30
    DeletionPolicy: Retain

  #########################################
  # ECS Cluster
  #########################################
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ecs-teste
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
        - EC2ManagedInstances
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: EC2ManagedInstances
          Weight: 1

  #########################################
  # IAM Role: Instance Role (ECS + SSM)
  #########################################
  ECSInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ECSInstanceRole

  #########################################
  # Launch Template para Managed Instances do ECS
  #########################################
  ECSLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref ECSAMI
        InstanceType: t3.micro
        IamInstanceProfile:
          Arn: !GetAtt ECSInstanceProfile.Arn
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
        Monitoring:
          Enabled: true

  #########################################
  # Auto Scaling Group dos Managed Instances
  #########################################
  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: "1"
      MaxSize: "3"
      DesiredCapacity: "1"
      VPCZoneIdentifier:
        - subnet-123456
        - subnet-654321
      LaunchTemplate:
        LaunchTemplateId: !Ref ECSLaunchTemplate
        Version: !GetAtt ECSLaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: ecs-managed-instance
          PropagateAtLaunch: true

  #########################################
  # ECS Capacity Provider (EC2 Managed Instances)
  #########################################
  EC2CapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties:
      Name: EC2ManagedInstances
      AutoScalingGroupProvider:
        AutoScalingGroupArn: !Ref ECSAutoScalingGroup
        ManagedScaling:
          Status: ENABLED
          TargetCapacity: 80
        ManagedTerminationProtection: DISABLED
