AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Cluster – Self-Managed Instances"

Parameters:
  ECSAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id

Resources:

  #########################################
  # Log Group
  #########################################
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/self-managed
      RetentionInDays: 30
    DeletionPolicy: Retain

  #########################################
  # ECS Cluster
  #########################################
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ecs-selfmanaged
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT

  #########################################
  # IAM Role para Instâncias EC2 do ECS
  #########################################
  ECSInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ECSInstanceRole

  #########################################
  # Launch Template (usado se você subir EC2 manual)
  #########################################
  ECSSelfManagedLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref ECSAMI
        InstanceType: t3.micro
        IamInstanceProfile:
          Arn: !GetAtt ECSInstanceProfile.Arn
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo ECS_CLUSTER=${ECSCluster} >> /etc/ecs/ecs.config
        Monitoring:
          Enabled: true

Outputs:
  ClusterName:
    Value: !Ref ECSCluster
    Description: Nome do cluster ECS

  LaunchTemplateId:
    Value: !Ref ECSSelfManagedLaunchTemplate
    Description: Launch Template para criar EC2 manualmente
