AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Fargate - Template mínimo"

Resources:
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/ecs-teste
      RetentionInDays: 30
    DeletionPolicy: Retain

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ecs-teste
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1